### ISSUE TITLE
Could you please provide a sample pose sequence

### ISSUE THREAD

**Issue by Zhangjzh** [jsnln/fite#2]
I was trying to follow insturctions bellow.

To animate a certain subject, say rp_carla_posed_004, prepare a pose sequence (.npz files containing the pose and transl parameters) under the directory data_scans/rp_carla_posed_004/test/

I don't know what the pose sequence(.npz files) should be like. Could you please provide a sample pose sequence?
Thanks very much!

**Comment by jsnln** [comment]
Hi. The detailed description of what these .npz files should be can be found in [**Data Preparation for Training**](https://github.com/jsnln/fite#2-data-preparation-for-training) under the section **The Whole Pipeline** in the README. Note that for inference only two keys (`pose` and `transl`) are needed.

You can also use the pose sequences in [CAPE](https://cape.is.tue.mpg.de/dataset.html), whose format is consistent with ours (for inference, not training). However, we cannot directly provide them due to copyright restrictions.

**Comment by Zhangjzh** [comment]
Thanks you for your prompt reply!

Besides, I generate the T-pose SMPL mesh by setting pose and shape parameters to zero. Is this correct?

**Comment by jsnln** [comment]
> Besides, I generate the T-pose SMPL mesh by setting pose and shape parameters to zero. Is this correct?

Yes, the T-pose SMPL should have zero pose parameters. But I am not sure about using zero shape parameters. Shape parameters should be selected to match your training data. Normally this can be obtained by keypoints-based SMPL fitting methods.

In our work, we have used the ground truth SMPLX meshes provided in [ReSynth](https://pop.is.tue.mpg.de/index.html), and applied the [SMPLX-to-SMPL transfer model here](https://github.com/vchoutas/smplx/tree/main/transfer_model) to obtain shape and pose parameters.
